org 0x875EBFC
	.word sprite_10_gfx
	.word sprite_11_gfx
	.word sprite_12_gfx
	.word sprite_13_gfx
	.word sprite_14_gfx
	.word sprite_15_gfx
	.word sprite_16_gfx
	.word sprite_17_gfx
	.word sprite_18_gfx
	.word sprite_19_gfx
	.word sprite_1A_gfx
	.word sprite_1B_gfx
	.word sprite_1C_gfx
	.word sprite_1D_gfx
	.word sprite_1E_gfx
	.word sprite_1F_gfx
	.word sprite_20_gfx
	.word sprite_21_gfx
	.word sprite_22_gfx
	.word sprite_23_gfx
	.word sprite_24_gfx
	.word sprite_25_gfx
	.word sprite_26_gfx
	.word sprite_27_gfx
	.word sprite_28_gfx
	.word sprite_29_gfx
	.word sprite_2A_gfx
	.word sprite_2B_gfx
	.word sprite_2C_gfx
	.word sprite_2D_gfx
	.word sprite_2E_gfx
	.word sprite_2F_gfx
	.word sprite_30_gfx
	.word sprite_31_gfx
	.word sprite_32_gfx
	.word sprite_33_gfx
	.word sprite_34_gfx
	.word sprite_35_gfx
	.word sprite_36_gfx
	.word sprite_37_gfx
	.word sprite_38_gfx
	.word sprite_39_gfx
	.word sprite_3A_gfx
	.word sprite_3B_gfx
	.word sprite_3C_gfx
	.word sprite_3D_gfx
	.word sprite_3E_gfx
	.word sprite_3F_gfx
	.word sprite_40_gfx
	.word sprite_41_gfx
	.word sprite_42_gfx
	.word sprite_43_gfx
	.word sprite_44_gfx
	.word sprite_45_gfx
	.word sprite_46_gfx
	.word sprite_47_gfx
	.word sprite_48_gfx
	.word sprite_49_gfx
	.word sprite_4A_gfx
	.word sprite_4B_gfx
	.word sprite_4C_gfx
	.word sprite_4D_gfx
	.word sprite_4E_gfx
	.word sprite_4F_gfx
	.word sprite_50_gfx
	.word sprite_51_gfx
	.word sprite_52_gfx
	.word sprite_53_gfx
	.word sprite_54_gfx
	.word sprite_55_gfx
	.word sprite_56_gfx
	.word sprite_57_gfx
	.word sprite_58_gfx
	.word sprite_59_gfx
	.word sprite_5A_gfx
	.word sprite_5B_gfx
	.word sprite_5C_gfx
	.word sprite_5D_gfx
	.word sprite_5E_gfx
	.word sprite_5F_gfx
	.word sprite_60_gfx
	.word sprite_61_gfx
	.word sprite_62_gfx
	.word sprite_63_gfx
	.word sprite_64_gfx
	.word sprite_65_gfx
	.word sprite_66_gfx
	.word sprite_67_gfx
	.word sprite_68_gfx
	.word sprite_69_gfx
	.word sprite_6A_gfx
	.word sprite_6B_gfx
	.word sprite_6C_gfx
	.word sprite_6D_gfx
	.word sprite_6E_gfx
	.word sprite_6F_gfx
	.word sprite_70_gfx
	.word sprite_71_gfx
	.word sprite_72_gfx
	.word sprite_73_gfx
	.word sprite_74_gfx
	.word sprite_75_gfx
	.word sprite_76_gfx
	.word sprite_77_gfx
	.word sprite_78_gfx
	.word sprite_79_gfx
	.word sprite_7A_gfx
	.word sprite_7B_gfx
	.word sprite_7C_gfx
	.word sprite_7D_gfx
	.word sprite_7E_gfx
	.word sprite_7F_gfx
	.word sprite_80_gfx
	.word sprite_81_gfx
	.word sprite_82_gfx
	.word sprite_83_gfx
	.word sprite_84_gfx
	.word sprite_85_gfx
	.word sprite_86_gfx
	.word sprite_87_gfx
	.word sprite_88_gfx
	.word sprite_89_gfx
	.word sprite_8A_gfx
	.word sprite_8B_gfx
	.word sprite_8C_gfx
	.word sprite_8D_gfx
	.word sprite_8E_gfx
	.word sprite_8F_gfx
	.word sprite_90_gfx
	.word sprite_91_gfx
	.word sprite_92_gfx
	.word sprite_93_gfx
	.word sprite_94_gfx
	.word sprite_95_gfx
	.word sprite_96_gfx
	.word sprite_97_gfx
	.word sprite_98_gfx
	.word sprite_99_gfx
	.word sprite_9A_gfx
	.word sprite_9B_gfx
	.word sprite_9C_gfx
	.word sprite_9D_gfx
	.word sprite_9E_gfx
	.word sprite_9F_gfx
	.word sprite_A0_gfx
	.word sprite_A1_gfx
	.word sprite_A2_gfx
	.word sprite_A3_gfx
	.word sprite_A4_gfx
	.word sprite_A5_gfx
	.word sprite_A6_gfx
	.word sprite_A7_gfx
	.word sprite_A8_gfx
	.word sprite_A9_gfx
	.word sprite_AA_gfx
	.word sprite_AB_gfx
	.word sprite_AC_gfx
	.word sprite_AD_gfx
	.word sprite_AE_gfx
	.word sprite_AF_gfx
	.word sprite_B0_gfx
	.word sprite_B1_gfx
	.word sprite_B2_gfx
	.word sprite_B3_gfx
	.word sprite_B4_gfx
	.word sprite_B5_gfx
	.word sprite_B6_gfx
	.word sprite_B7_gfx
	.word sprite_B8_gfx
	.word sprite_B9_gfx
	.word sprite_BA_gfx
	.word sprite_BB_gfx
	.word sprite_BC_gfx
	.word sprite_BD_gfx
	.word sprite_BE_gfx
	.word sprite_BF_gfx
	.word sprite_C0_gfx
	.word sprite_C1_gfx
	.word sprite_C2_gfx
	.word sprite_C3_gfx
	.word sprite_C4_gfx
	.word sprite_C5_gfx
	.word sprite_C6_gfx
	.word sprite_C7_gfx
	.word sprite_C8_gfx
	.word sprite_C9_gfx
	.word sprite_CA_gfx
	.word sprite_CB_gfx
	.word sprite_CC_gfx

org 0x875EEF4
	.word sprite_10_pal
	.word sprite_11_pal
	.word sprite_12_pal
	.word sprite_13_pal
	.word sprite_14_pal
	.word sprite_15_pal
	.word sprite_16_pal
	.word sprite_17_pal
	.word sprite_18_pal
	.word sprite_19_pal
	.word sprite_1A_pal
	.word sprite_1B_pal
	.word sprite_1C_pal
	.word sprite_1D_pal
	.word sprite_1E_pal
	.word sprite_1F_pal
	.word sprite_20_pal
	.word sprite_21_pal
	.word sprite_22_pal
	.word sprite_23_pal
	.word sprite_24_pal
	.word sprite_25_pal
	.word sprite_26_pal
	.word sprite_27_pal
	.word sprite_28_pal
	.word sprite_29_pal
	.word sprite_2A_pal
	.word sprite_2B_pal
	.word sprite_2C_pal
	.word sprite_2D_pal
	.word sprite_2E_pal
	.word sprite_2F_pal
	.word sprite_30_pal
	.word sprite_31_pal
	.word sprite_32_pal
	.word sprite_33_pal
	.word sprite_34_pal
	.word sprite_35_pal
	.word sprite_36_pal
	.word sprite_37_pal
	.word sprite_38_pal
	.word sprite_39_pal
	.word sprite_3A_pal
	.word sprite_3B_pal
	.word sprite_3C_pal
	.word sprite_3D_pal
	.word sprite_3E_pal
	.word sprite_3F_pal
	.word sprite_40_pal
	.word sprite_41_pal
	.word sprite_42_pal
	.word sprite_43_pal
	.word sprite_44_pal
	.word sprite_45_pal
	.word sprite_46_pal
	.word sprite_47_pal
	.word sprite_48_pal
	.word sprite_49_pal
	.word sprite_4A_pal
	.word sprite_4B_pal
	.word sprite_4C_pal
	.word sprite_4D_pal
	.word sprite_4E_pal
	.word sprite_4F_pal
	.word sprite_50_pal
	.word sprite_51_pal
	.word sprite_52_pal
	.word sprite_53_pal
	.word sprite_54_pal
	.word sprite_55_pal
	.word sprite_56_pal
	.word sprite_57_pal
	.word sprite_58_pal
	.word sprite_59_pal
	.word sprite_5A_pal
	.word sprite_5B_pal
	.word sprite_5C_pal
	.word sprite_5D_pal
	.word sprite_5E_pal
	.word sprite_5F_pal
	.word sprite_60_pal
	.word sprite_61_pal
	.word sprite_62_pal
	.word sprite_63_pal
	.word sprite_64_pal
	.word sprite_65_pal
	.word sprite_66_pal
	.word sprite_67_pal
	.word sprite_68_pal
	.word sprite_69_pal
	.word sprite_6A_pal
	.word sprite_6B_pal
	.word sprite_6C_pal
	.word sprite_6D_pal
	.word sprite_6E_pal
	.word sprite_6F_pal
	.word sprite_70_pal
	.word sprite_71_pal
	.word sprite_72_pal
	.word sprite_73_pal
	.word sprite_74_pal
	.word sprite_75_pal
	.word sprite_76_pal
	.word sprite_77_pal
	.word sprite_78_pal
	.word sprite_79_pal
	.word sprite_7A_pal
	.word sprite_7B_pal
	.word sprite_7C_pal
	.word sprite_7D_pal
	.word sprite_7E_pal
	.word sprite_7F_pal
	.word sprite_80_pal
	.word sprite_81_pal
	.word sprite_82_pal
	.word sprite_83_pal
	.word sprite_84_pal
	.word sprite_85_pal
	.word sprite_86_pal
	.word sprite_87_pal
	.word sprite_88_pal
	.word sprite_89_pal
	.word sprite_8A_pal
	.word sprite_8B_pal
	.word sprite_8C_pal
	.word sprite_8D_pal
	.word sprite_8E_pal
	.word sprite_8F_pal
	.word sprite_90_pal
	.word sprite_91_pal
	.word sprite_92_pal
	.word sprite_93_pal
	.word sprite_94_pal
	.word sprite_95_pal
	.word sprite_96_pal
	.word sprite_97_pal
	.word sprite_98_pal
	.word sprite_99_pal
	.word sprite_9A_pal
	.word sprite_9B_pal
	.word sprite_9C_pal
	.word sprite_9D_pal
	.word sprite_9E_pal
	.word sprite_9F_pal
	.word sprite_A0_pal
	.word sprite_A1_pal
	.word sprite_A2_pal
	.word sprite_A3_pal
	.word sprite_A4_pal
	.word sprite_A5_pal
	.word sprite_A6_pal
	.word sprite_A7_pal
	.word sprite_A8_pal
	.word sprite_A9_pal
	.word sprite_AA_pal
	.word sprite_AB_pal
	.word sprite_AC_pal
	.word sprite_AD_pal
	.word sprite_AE_pal
	.word sprite_AF_pal
	.word sprite_B0_pal
	.word sprite_B1_pal
	.word sprite_B2_pal
	.word sprite_B3_pal
	.word sprite_B4_pal
	.word sprite_B5_pal
	.word sprite_B6_pal
	.word sprite_B7_pal
	.word sprite_B8_pal
	.word sprite_B9_pal
	.word sprite_BA_pal
	.word sprite_BB_pal
	.word sprite_BC_pal
	.word sprite_BD_pal
	.word sprite_BE_pal
	.word sprite_BF_pal
	.word sprite_C0_pal
	.word sprite_C1_pal
	.word sprite_C2_pal
	.word sprite_C3_pal
	.word sprite_C4_pal
	.word sprite_C5_pal
	.word sprite_C6_pal
	.word sprite_C7_pal
	.word sprite_C8_pal
	.word sprite_C9_pal
	.word sprite_CA_pal
	.word sprite_CB_pal
	.word sprite_CC_pal
